### PR TITLE
Introduce stub of a exclusive parameter for File.create.

### PR DESCRIPTION
**Pull request by aam**
This is to soften landing of a breaking change https://github.com/dart-lang/sdk/issues/49647

### CODE REVIEW

**Comment by aam** [comment]
@kevmoo can you please help with getting this reviewed?
(Windows bots seems to be failing for a while now).

**Review by dnfield — APPROVED** [review]
Lgtm. Can you bump the pubspec and update the changelog before landing?

**Comment by aam** [comment]
> Lgtm. Can you bump the pubspec and update the changelog before landing?

Thank you, done.

**Comment by jathak** [comment]
Is there a reason why this breaking change did not increase the major version? This [broke our build](https://github.com/sass/migrator/runs/7927427299?check_suite_focus=true) because node_io doesn't yet support this new parameter.

**Pull request merged**
