### PR TITLE
populate the pubspec repository fields; update readme

### PR DESCRIPTION
**Pull request by devoncarew**
- populate the pubspec repository fields
- update the two readmes with markdown badges
- add a top-level readme
- remove the top-level pubspec file (and push the analysis options configuration down into the the two monorepo packages)

The `repository` field changes are the most important here - we'd like this information to be populated for packages which get dep'd into the dart sdk repo.

### CODE REVIEW

**Comment by devoncarew** [comment]
cc @gspencergoog

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks!

**Comment by devoncarew** [comment]
Thanks for the review! Can you merge this (I don't have rights in this repo)?

**Comment by gspencergoog** [comment]
Sure, once the tests pass.

**Comment by devoncarew** [comment]
Can you re-kick the bots? I'm not sure what's going on with the windows github actions ones.

**Comment by devoncarew** [comment]
I kicked the bots with a whitespace change; it looks like the windows bots may no longer be passing:

https://github.com/google/file.dart/issues/197

**Pull request closed without merging**
