### PR TITLE
[null-safety] remove implicit-dynamic, intl in preparation for null-safety

### PR DESCRIPTION
**Pull request by jonahwilliams**
* Implicit dynamic is removed, which will make it easier to migrate to null-safety where it is not supported.
* Intl dependency is removed, since this will block null safety despite being used in only a single place.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I tested on ToT and the two windows tests are currently failing, is that expected?

**Comment by dnfield** [comment]
@jamesderlin has been working on that

**Comment by tvolkert** [comment]
Can you bump the version and update the CHANGELOG as well?

**Comment by jonahwilliams** [comment]
Changelog is updated - we're still on a unreleased dev version so that should be OK, right?

**Comment by jamesderlin** [comment]
> @jamesderlin has been working on that

All of my fixes for flaky tests should be in already.  I don't know why the current tests are failing.  Are they also flaky?  I didn't hit failures in my pending PR.

**Comment by tvolkert** [comment]
It's possible they were broken by a change in Dart, since this package doesn't pin its Dart version that it uses to run tests.

**Comment by jamesderlin** [comment]
I triggered a re-test of my pending PR, and it also failed on the same two tests.  The two failing tests both involve overwriting a symlink with a file and expecting that the operation clobbers the symlink's target instead of the symlink itself.  TBH, that expectation surprises me (but it seems to be normal POSIX behavior).  Clobbering the symlink itself seems like a reasonable choice too, so it seems plausible to me that either Windows changed its behavior or that the Dart SDK changed to better follow usual platform behavior. (I don't have a Windows 10 machine handy to see check what Windows normally does.)

**Comment by jonahwilliams** [comment]
Going to ignore the test failures in this PR. We can decided to update the test expectations or adjust the package in a future change

**Pull request merged**
