### PR TITLE
release version 7.0.0

### PR DESCRIPTION
**Pull request by jakemac53**

### CODE REVIEW

**Comment by devoncarew** [comment]
For posterity, here are the commits in the roll that's having problems:

```
file (https://github.com/google/file.dart/compare/e90e5ed..f05f5db):
  f05f5db  2023-05-15  James D. Lin  Make MemoryFile.openRead and _ChrootFile.openRead return Stream<List<int>> again (#217)
  f2f3076  2023-05-12  Ross Wang  MemoryFileSystem addStream onError (#220)
  5e76f74  2023-05-12  James D. Lin  Fix MemoryFileSystem to treat an empty path as non-existent (#213)
  7941466  2023-05-12  James D. Lin  Make `FileSystem.isLink` actually work (#214)
```

**Comment by jakemac53** [comment]
I landed a fix upstream, there was a broken code branch that used to be dead code, but the fixes for `isLink` caused it to no longer be dead code, and cause an actual failure, 🤣 . So no major issues, just fixing some bad code.

**Comment by jakemac53** [comment]
@gspencergoog can you review this?

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Pull request merged**
